project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: About
      - about.qmd
        text: Labs
      - Labs.qmd
        text: Project
      - Project.qmd
        text: Presentation
      -Presentation.qmd
      
format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

